### ISSUE TITLE
Wrong Duration under Backend Simply Explained

### ISSUE THREAD

**Issue by Gyanaa-Vaibhav** [jamezmca/learn-to-code#3]
<img width="684" alt="Screenshot 2024-09-18 at 3 06 08 PM" src="https://github.com/user-attachments/assets/3c1ee289-e69c-4404-b7b0-b574d8340124">

The website says the duration is 12 Minutes but the actual video is 21 Mins (20:38)

<img width="934" alt="Screenshot 2024-09-18 at 3 07 16 PM" src="https://github.com/user-attachments/assets/3a943bda-af30-4d1a-b2a8-2db828cf7704">

Same with the Readme.MD

**Comment by Gyanaa-Vaibhav** [comment]
if you don't mind I am just starting out can I try to fix it, I can change it in the readme and also I will put a pull request fixing the readme but I don't know if this is the same website repo

**Comment by jamezmca** [comment]
Thanks for pointing that out! I have updated the readme.md file with the correct duration :D

**Comment by Gyanaa-Vaibhav** [comment]
Do I have to click on close pull request? in the pull request page?

**Comment by jamezmca** [comment]
I have closed it :D Thanks again for pointing that out! Well spotted
